[package]
name = "vimetal"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.1", features = ["luajit", "macros"] }
nvim-oxi = { version = "0.5.1", features = ["mlua", "neovim-0-10"] }
